import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import {join} from 'node:path';
const root=fileURLToPath(new URL('..',import.meta.url));
const read=(p)=>readFile(join(root,p),'utf8');
const app=await read('assets/app.js'),css=await read('assets/styles.css'),edge=await read('supabase/functions/identity-provisioning/index.ts');
const orgMigration=await read('supabase/migrations/20260806163000_phase5_4_organization_control_center.sql');
const identityGuard=await read('supabase/migrations/20260806164500_phase5_4_identity_delegation_guard.sql');
const mutationSurface=await read('supabase/migrations/20260806165500_phase5_4_organization_mutation_surface.sql');
const provisioningBackstop=await read('supabase/migrations/20260806170500_phase5_4_provisioning_backstop.sql');
const settingsValidation=await read('supabase/migrations/20260806171500_phase5_4_company_branding_validation.sql');
const pkg=JSON.parse(await read('package.json'));
assert.equal(pkg.version,'6.9.0');
for(const contract of ['ORGANIZATION CONTROL CENTER','team-member-card','role-studio-card','settings-command-center','data-live-settings','BroadcastChannel','applyTeamFilters','applyRoleFilters','updateSettingsLivePreview','memberAccountState','canDelegateRoleClient',"['invited','active','suspended',m.status]", "Final departure uses the Offboarding plan"]) assert.ok(app.includes(contract),`Missing app contract: ${contract}`);
for(const contract of ['Phase 5.4 — Organization Control Center','.org-hero','.team-directory','.role-studio-grid','.settings-command-center','.brand-live-preview','.member-control-layout','.role-editor-layout','@media(prefers-reduced-motion:reduce)']) assert.ok(css.includes(contract),`Missing CSS contract: ${contract}`);
for(const contract of ['can_delegate_permissions','validate_company_membership_scope','Company must keep at least one owner','member.role_changed','member.status_changed','memberships_company_employee_code_active_uidx']) assert.ok(orgMigration.includes(contract),`Missing organization guard: ${contract}`);
for(const contract of ['service_validate_member_provisioning','user_has_company_permission','You cannot assign a role with permissions you do not hold','Member management permission required for permission overrides']) assert.ok(identityGuard.includes(contract),`Missing provisioning guard: ${contract}`);
for(const policy of ['companies_update_manage','company_branding_insert','compensation_update']) assert.ok(mutationSurface.includes(`drop policy if exists ${policy}`));
for(const contract of ['validate_member_permission_override','can_delegate_role','service_validate_member_provisioning','Owner role cannot be assigned through member provisioning']) assert.ok(provisioningBackstop.includes(contract),`Missing provisioning backstop: ${contract}`);
for(const contract of ['companies_official_email_format_check','companies_website_format_check','company_branding_app_name_check','Unknown company fields','Unknown branding fields','Brand colors must use #RRGGBB format','organization_control_center']) assert.ok(settingsValidation.includes(contract),`Missing settings validation: ${contract}`);
assert.match(edge,/service_validate_member_provisioning/);
assert.match(edge,/set_member_permission_override/);
assert.doesNotMatch(edge,/admin\.from\("member_permission_overrides"\)\.upsert/);
assert.equal(app,await read('public/assets/app.js'));
assert.equal(css,await read('public/assets/styles.css'));
assert.equal(css,await read('app/globals.css'));
console.log('Phase 5.4 organization control center contract passed.');
