import fs from 'node:fs';
import crypto from 'node:crypto';
const read=(p)=>fs.readFileSync(p,'utf8');
const buf=(p)=>fs.readFileSync(p);
const ok=(c,m)=>{if(!c)throw new Error(m)};
const app=read('assets/app.js'), org=read('assets/organization-os.js'), css=read('assets/styles.css'), platform=read('platform-console/assets/platform.js');
const pkg=JSON.parse(read('package.json'));
const mig=read('supabase/migrations/20260807190000_phase5_8_organization_os_closure.sql');
const trigger=read('supabase/migrations/20260807190500_phase5_8_runtime_trigger_fix.sql');
const security=read('supabase/migrations/20260807191000_phase5_8_member_security_snapshot_reproducible.sql');
const health=read('supabase/migrations/20260807191500_phase5_8_health_admin_gate.sql');
const accessGate=read('supabase/migrations/20260807192000_phase5_8_member_access_snapshot_admin_gate.sql');
const bulkEnum=read('supabase/migrations/20260807192500_phase5_8_bulk_status_enum_fix.sql');
const bulkPermission=read('supabase/migrations/20260807193000_phase5_8_bulk_permission_source_fix.sql');
const savedViewsLint=read('supabase/migrations/20260807193500_phase5_8_saved_views_lint_cleanup.sql');
ok(pkg.version==='6.9.0','package must be 6.9.0');
ok(app.includes("./organization-os.js?v=6.9.0"),'Organization OS import/cache key missing');
ok(app.includes("organization:'company.manage'"),'Organization OS route must require company.manage');
ok(app.includes("['organization','building'"),'Organization navigation item missing');
for(const needle of ['MEMBER 360°','Workspace Setup Journey','Organization Health Center','orgos-saved-view','orgos-bulk-bar','organization_runtime_revision','roleInsights','commandQuickActions','syncRemote']) ok(org.includes(needle),`Organization OS missing ${needle}`);
for(const needle of ['workspace_saved_views','company_work_settings','member_work_preferences','organization_runtime_versions','organization_health_snapshot','bulk_set_member_role','bulk_set_member_status','bulk_restore_member_access','save_company_work_settings']) ok(mig.includes(needle),`5.8 migration missing ${needle}`);
for(const needle of ["tg_table_name='companies'","tg_table_name='role_permissions'","tg_table_name='role_addon_permissions'","tg_table_name='organization_unit_memberships'","tg_table_name='member_permission_overrides'","tg_table_name='member_role_addons'"]) ok(trigger.includes(needle),`runtime trigger fix missing ${needle}`);
ok(security.includes('member_security_snapshot'),'member security snapshot is not reproducible');
ok(health.includes("company.manage")&&health.includes('organization_health_snapshot'),'health RPC must be management-gated');
ok(accessGate.includes('members.manage')&&accessGate.includes('roles.manage')&&accessGate.includes('m.user_id=auth.uid()'),'View as User backend gate missing');
ok(bulkEnum.includes('::public.membership_status')&&!bulkEnum.includes('public.has_company_permission'),'bulk status must cast to membership_status and use the current permission engine');
ok(bulkPermission.includes('app_private.has_company_permission')&&!bulkPermission.includes('public.has_company_permission'),'bulk RPCs must use app_private permission source');
ok(savedViewsLint.includes('user_id = (select auth.uid())'),'saved-view RLS must use initplan-safe auth.uid()');
ok(savedViewsLint.includes('drop index if exists public.workspace_saved_views_one_default_idx'),'duplicate saved-view default index must be removed');
ok(platform.includes('organization_health_snapshot'),'Platform Console must use the same organization health engine');
ok(app.includes('setInterval')&&app.includes('syncRemote'),'cross-session organization revision polling missing');
ok(app.includes('function openQuickCreate()')&&app.includes('data-action=\"quick-create\"'),'permission-aware Quick Create missing');
ok(app.includes('function canInspectMemberAccess(m)'),'member access inspection gate helper missing');
for(const needle of ['orgos-readiness','orgos-health-issue','orgos-member360','orgos-tree-node','orgos-bulk-bar','orgos-saved-view']) ok(css.includes(needle),`premium Organization OS style missing ${needle}`);
const equal=(a,b)=>crypto.createHash('sha256').update(buf(a)).digest('hex')===crypto.createHash('sha256').update(buf(b)).digest('hex');
for(const [a,b] of [['assets/app.js','public/assets/app.js'],['assets/organization-os.js','public/assets/organization-os.js'],['assets/styles.css','public/assets/styles.css'],['assets/styles.css','app/globals.css'],['assets/styles.css','platform-console/assets/styles.css'],['assets/platform.js','public/assets/platform.js'],['assets/platform.js','platform-console/assets/platform.js'],['assets/api.js','public/assets/api.js'],['assets/api.js','platform-console/assets/api.js']]) ok(equal(a,b),`runtime mirror drift: ${a} != ${b}`);
console.log('PASS organization-os-5.8: integrated Organization OS contracts verified');
