import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {dirname,resolve} from 'node:path';
import {fileURLToPath} from 'node:url';
import {normalizeEngineeringSnapshot,engineeringSnapshotSvg,exportEngineeringDxfCompatible} from '../assets/engineering.js';

const root=resolve(dirname(fileURLToPath(import.meta.url)),'..');
const out=resolve(root,'docs/samples');
await mkdir(out,{recursive:true});
const seed=JSON.parse(await readFile(resolve(out,'cad-freeze-4.13-snapshot.json'),'utf8'));
const snapshot=normalizeEngineeringSnapshot(seed.snapshot);
snapshot.nodes[0].labelText='MAIN CABINET 01\nODF 144 · PORT 01';
snapshot.nodes[0].labelOffset={x:0,y:92};
snapshot.nodes[1].labelText='بيانات كابينة فرعية قابلة للتحريك\nSUB CABINET 02';
snapshot.nodes[1].labelOffset={x:0,y:92};
snapshot.nodes[1].labelRotation=-8;
snapshot.nodes[2].labelText='TERMINATION BOX 01\nCORE 001–096';
snapshot.nodes[2].labelOffset={x:0,y:72};
snapshot.nodes[3].labelText='TB-02\nCORE 097–192';
snapshot.nodes[3].labelOffset={x:0,y:72};
snapshot.routes[0].labelRotation=-4;
snapshot.annotations.push({id:'qa-note',x:1220,y:870,text:'ISSUED DRAWING\nرسم جاهز للطباعة',size:20,rotation:-6,align:'middle',flipX:false,flipY:false,bold:true,background:true,lineHeight:1.25});
const logo="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 120 55'%3E%3Crect width='120' height='55' rx='7' fill='%23137A55'/%3E%3Ctext x='60' y='34' text-anchor='middle' font-family='Arial' font-size='18' fill='white'%3EOPTIMUM%3C/text%3E%3C/svg%3E";
const reference="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 800 500'%3E%3Cpath d='M30 430 L250 90 L470 390 L720 80' fill='none' stroke='%2394a3b8' stroke-width='8' stroke-dasharray='18 14'/%3E%3Ctext x='400' y='250' text-anchor='middle' font-family='Arial' font-size='32' fill='%2364748b'%3EREFERENCE SKETCH%3C/text%3E%3C/svg%3E";
snapshot.reference={assetId:'qa-reference',opacity:.13,locked:true,mimeType:'image/svg+xml',fit:'contain',offsetX:0,offsetY:0,scale:1,rotation:0};
const settings={...seed.settings,titleBlock:true,titleBlockData:{...(seed.settings.titleBlockData||{}),projectCode:'P001',client:'Optimum Client',consultant:'Engineering Consultant',mainContractor:'Main Contractor',subContractor:'Optimum Engineering',designer:'Eng. A',checkedBy:'Eng. B',approvedBy:'Eng. C',logos:[{src:logo,width:120,height:55}]}};
const metadata={...seed.metadata,drawingNo:'P001-FIBER-001',title:'Secondary Fiber Network — Production Freeze',revision:'R2',status:'FOR APPROVAL',date:'2026-08-05'};
const svg=engineeringSnapshotSvg(snapshot,{settings,catalog:seed.catalog,metadata,locale:'ar',referenceUrl:reference,validation:{issues:[],errorCount:0,warningCount:0,suggestionCount:0}});
const dxf=exportEngineeringDxfCompatible(snapshot,{...metadata,catalog:seed.catalog},{...settings,catalog:seed.catalog});
await writeFile(resolve(out,'cad-production-4.14-demo.svg'),svg);
await writeFile(resolve(out,'cad-production-4.14-demo.dxf'),dxf);
await writeFile(resolve(out,'cad-production-4.14-snapshot.json'),JSON.stringify({snapshot,settings,metadata,catalog:seed.catalog},null,2));
await writeFile(resolve(out,'cad-production-4.14-preview.html'),`<!doctype html><html lang="ar" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>CAD 4.14 QA</title><style>@page{size:A3 landscape;margin:5mm}html,body{margin:0;background:#07131f;font-family:Arial,sans-serif}.qa{padding:18px}.qa h1{margin:0 0 12px;color:#fff;font-size:18px}.sheet{background:#fff;box-shadow:0 20px 55px #0008}.sheet svg{display:block;width:100%;height:auto}@media print{html,body{background:#fff}.qa{padding:0}.qa h1{display:none}.sheet{width:410mm;height:287mm;display:flex;align-items:center;box-shadow:none}.sheet svg{width:100%;height:100%}}</style></head><body><main class="qa"><h1>Optimum CAD 4.14 — Production Print Preview</h1><div class="sheet">${svg}</div></main></body></html>`);
console.log('Generated Phase 4.14 production samples.');
