import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import {join} from 'node:path';
const root=fileURLToPath(new URL('..',import.meta.url));
const read=(p)=>readFile(join(root,p),'utf8');
const js=await read('assets/engineering.js'),css=await read('assets/styles.css'),html=await read('docs/samples/cad-usability-4.11-preview.html'),dxf=await read('docs/samples/cad-usability-4.11-demo.dxf'),svg=await read('docs/samples/cad-usability-4.11-demo.svg');
assert.match(js,/cad-workspace-nav/);
assert.match(js,/data-action="engineering-open-files"/);
assert.match(js,/data-action="engineering-save-to-files"/);
assert.match(js,/bindPanelResizers/);
assert.match(js,/optimum\.cad\.paletteWidth/);
assert.match(js,/optimum\.cad\.routeDockHeight/);
assert.match(js,/route:\$\{symbol\|\|item\?\.code/);
assert.doesNotMatch(js,/\['عناصر أخرى','Other nodes'/);
assert.match(css,/Phase 4\.11/);
assert.match(css,/cad-resize-palette/);
assert.match(css,/grid-template-rows:repeat\(2/);
assert.match(html,/cad-header-411/);
assert.match(html,/cad-resize-route/);
assert.match(html,/engineering-open-files/);
assert.match(svg,/eng-route-label-text/);
assert.match(svg,/eng-route-halo/);
assert.match(svg,/eng-route-ink/);
assert.doesNotMatch(svg,/eng-route-label-box/);
assert.match(dxf,/\$ACADVER\r?\n1\r?\nAC1009/);
assert.match(dxf,/0\r?\nLINE\r?\n/);
assert.match(dxf,/0\r?\nTEXT\r?\n/);
const lines=dxf.trimEnd().split(/\r?\n/);assert.equal(lines.length%2,0);for(let i=0;i<lines.length;i+=2)assert.match(lines[i],/^-?\d+$/);
assert.equal(lines.at(-2),'0');assert.equal(lines.at(-1),'EOF');
console.log('✓ Phase 4.11 header, internal Files save, resizable panels, complete route library, text-only labels and legacy R12 sample checks passed');
