import fs from 'node:fs';
import assert from 'node:assert/strict';

const read = path => fs.readFileSync(new URL(`../${path}`, import.meta.url), 'utf8');
const shell = read('src/v7/components/Shell.js');
const dashboard = read('src/v7/pages/DashboardPage.js');
const work = read('src/v7/pages/WorkPage.js');
const projects = read('src/v7/pages/ProjectsPage.js');
const detail = read('src/v7/pages/ProjectDetailPage.js');
const documents = read('src/v7/pages/DocumentsPage.js');
const people = read('src/v7/pages/PeoplePage.js');
const delivery = read('src/v7/pages/DeliveryPage.js');
const control = read('src/v7/pages/ControlPage.js');
const css = read('src/v7/v7.css');

assert.match(shell, /const navGroups\s*=/);
assert.match(shell, /v7-nav-group/);
assert.match(dashboard, /v7-dashboard-hero/);
assert.match(dashboard, /\/v7\/work\?due=overdue/);
assert.match(dashboard, /\/v7\/work\?status=blocked/);
assert.match(dashboard, /v7-capacity-card/);
assert.match(work, /requestedDue/);
assert.match(work, /due:\s*dueFilter/);
assert.match(projects, /v7-portfolio-pulse/);
assert.match(projects, /v7-project-card--premium/);
assert.match(projects, /offset:\s*page\s*\*\s*PAGE_SIZE/);
assert.match(detail, /v7-entity-hero/);
assert.match(documents, /v7-cde-context/);
assert.match(documents, /v7-document-head/);
assert.match(documents, /document_search_v2/);
assert.match(documents, /const PAGE_SIZE\s*=\s*50/);
assert.match(work, /v7-work-pulse/);
assert.match(work, /v7-due-segments/);
assert.match(people, /v7-people-pulse/);
assert.match(people, /v7-people-head/);
assert.match(delivery, /v7-delivery-pulse/);
assert.match(delivery, /p_status:\s*status\s*\|\|\s*null/);
assert.match(delivery, /p_query:\s*debouncedQuery\s*\|\|\s*null/);
assert.match(delivery, /v7-delivery-head/);
assert.match(control, /v7-governance-hero/);
assert.match(css, /@media\(max-width:1180px\)/);
assert.match(css, /@media\(max-width:900px\)/);
assert.match(css, /@media\(max-width:680px\)/);
console.log('V7 premium UI 7.0 contract: PASS');
