import fs from 'node:fs';
import assert from 'node:assert/strict';
const css = fs.readFileSync(new URL('../src/v7/v7.css', import.meta.url), 'utf8');
const work = fs.readFileSync(new URL('../src/v7/pages/WorkPage.js', import.meta.url), 'utf8');
const people = fs.readFileSync(new URL('../src/v7/pages/PeoplePage.js', import.meta.url), 'utf8');
const delivery = fs.readFileSync(new URL('../src/v7/pages/DeliveryPage.js', import.meta.url), 'utf8');
assert.match(css, /V7 readability \+ responsive decision-surface pass/);
assert.match(css, /\.v7-eyebrow\{font-size:11px\}/);
assert.match(css, /\.v7-page-heading>p\{font-size:14px/);
assert.match(css, /\.v7-badge[^}]*font-size:11px/);
assert.match(css, /@media\(max-width:900px\)[\s\S]*\.v7-work-row\{min-width:0[\s\S]*grid-template-areas:"title status"/);
assert.match(css, /\.v7-people-list button\{min-width:0[\s\S]*grid-template-areas:"avatar person state"/);
assert.match(css, /\.v7-delivery-list>button\{min-width:0[\s\S]*grid-template-areas:"icon main state"/);
assert.match(work, /className="v7-work-context"/);
assert.match(work, /className="v7-work-due"/);
assert.match(people, /className="v7-person-role"/);
assert.match(people, /className="v7-person-scope"/);
assert.match(delivery, /aria-label=\{`\$\{p\.package_no/);
console.log('V7 readability + responsive 7.0 contract: PASS');
