import fs from 'node:fs';
import assert from 'node:assert/strict';
const read=p=>fs.readFileSync(p,'utf8');
const pkg=JSON.parse(read('package.json'));
const app=read('assets/app.js');
const pubApp=read('public/assets/app.js');
const work=read('assets/work-os.js');
const pubWork=read('public/assets/work-os.js');
const closure=read('supabase/migrations/20260808001000_phase6_6_work_delivery_os_release_closure.sql');
const schedulerFix=read('supabase/migrations/20260808002000_phase6_6_scheduler_company_authority_fix.sql');
const perfFix=read('supabase/migrations/20260808003000_phase6_6_work_performance_fk_indexes.sql');
const styles=read('assets/styles.css');
const pubStyles=read('public/assets/styles.css');
const appStyles=read('app/globals.css');
const platformStyles=read('platform-console/assets/styles.css');
assert.equal(pkg.version,'6.9.0');
assert.equal(app,pubApp,'app.js root/public drift');
assert.equal(work,pubWork,'work-os.js root/public drift');
assert.equal(styles,pubStyles,'styles root/public drift');
assert.equal(styles,appStyles,'styles root/app globals drift');
assert.equal(styles,platformStyles,'styles root/platform drift');
assert.match(app,/createWorkOS/);
assert.match(app,/workOS\?\.page\|\|tasksPage/);
assert.match(app,/calendar:workOS\?\.calendarPage/);
assert.match(app,/activity:workOS\?\.activityPage/);
assert.match(app,/open-search-result[^\n]*navigateToEntity|navigateToEntity\(type,id\)/,'global search must use unified entity navigation');
assert.match(app,/workOS\?\.openTask\(c\.task_id\)/,'unified entity navigation must deep-link tasks to Work OS');
for(const rpc of ['work_task_query','work_task_detail','work_assignment_candidates','work_delivery_snapshot','work_calendar_feed','work_activity_feed','work_runtime_revision','save_work_item','save_task_dependency','save_work_milestone','work_leave_requests','save_task_template','save_work_automation_rule']) assert.ok(work.includes(`'${rpc}'`),`Work OS missing RPC ${rpc}`);
assert.match(work,/expected_lock_version/,'optimistic locking not wired');
assert.match(work,/Blocked status requires|اكتب سبب التوقف|blocker reason/i,'blocked reason UX missing');
assert.match(work,/data-workos-activity-search/,'server activity search UI missing');
assert.match(work,/view:'month'/);assert.match(work,/week/);assert.match(work,/agenda/);assert.match(work,/capacity/);
assert.doesNotMatch(work,/materialize_recurring_tasks/,'browser must not materialize recurrence');
assert.match(closure,/create or replace function public\.save_work_item/);
assert.match(closure,/task_time_overlaps_approved_leave/);
assert.match(closure,/expected_lock_version/);
assert.match(closure,/task_dependencies_select[\s\S]*can_view_task\(blocker_task_id\) and app_private\.can_view_task\(blocked_task_id\)/);
assert.match(closure,/revoke select on table public\.task_dependencies,public\.task_watchers from authenticated/);
assert.match(closure,/work_scheduler_tick_internal/);
assert.match(closure,/cron\.schedule\('optimum-work-scheduler','\*\/15 \* \* \* \*'/);
assert.match(schedulerFix,/join public\.roles r[\s\S]*r\.slug='owner'/,'scheduler must use per-company owner authority');
assert.match(schedulerFix,/companies_skipped/);
assert.match(schedulerFix,/companies_failed/);
assert.match(perfFix,/tasks_owner_user_fk_idx/);
assert.match(perfFix,/task_dependencies_company_fk_idx/);
assert.match(perfFix,/member_leave_created_by_fk_idx/);
assert.match(pkg.scripts['test:browser'],/test:browser:core[\s\S]*test:browser:policy[\s\S]*test:browser:work/,'browser release gate must be split into deterministic groups');
for(const path of ['index.html','app/page.js','app/platform/page.js','assets/app.js','assets/api.js','platform-console/index.html']) assert.ok(read(path).includes('6.9.0'),`${path} missing 6.9.0 cache/version`);
console.log('Phase 6.6 Work & Delivery OS static closure checks passed.');
