create index if not exists access_change_requests_requested_by_idx on public.access_change_requests(requested_by);
create index if not exists access_change_requests_reviewed_by_idx on public.access_change_requests(reviewed_by);
create index if not exists access_governance_settings_updated_by_idx on public.access_governance_settings(updated_by);
create index if not exists access_scope_rules_created_by_idx on public.access_scope_rules(created_by);
create index if not exists access_scope_rules_permission_key_idx on public.access_scope_rules(permission_key);
create index if not exists company_entitlement_overrides_entitlement_idx on public.company_entitlement_overrides(entitlement_key);
create index if not exists company_entitlement_overrides_updated_by_idx on public.company_entitlement_overrides(updated_by);
create index if not exists company_memberships_alt_manager_idx on public.company_memberships(alternate_manager_user_id);
create index if not exists company_memberships_primary_site_idx on public.company_memberships(primary_site_id);
create index if not exists member_role_addons_addon_idx on public.member_role_addons(addon_id);
create index if not exists member_role_addons_assigned_by_idx on public.member_role_addons(assigned_by);
create index if not exists offboarding_plans_membership_idx on public.offboarding_plans(membership_id);
create index if not exists offboarding_plans_transfer_idx on public.offboarding_plans(transfer_to_membership_id);
create index if not exists offboarding_plans_created_by_idx on public.offboarding_plans(created_by);
create index if not exists offboarding_plans_approved_by_idx on public.offboarding_plans(approved_by);
create index if not exists offboarding_plans_executed_by_idx on public.offboarding_plans(executed_by);
create index if not exists organization_units_parent_idx on public.organization_units(parent_id);
create index if not exists organization_units_manager_idx on public.organization_units(manager_user_id);
create index if not exists organization_units_created_by_idx on public.organization_units(created_by);
create index if not exists resource_custody_company_idx on public.resource_custody(company_id);
create index if not exists resource_custody_custodian_idx on public.resource_custody(custodian_user_id);
create index if not exists resource_custody_assigned_by_idx on public.resource_custody(assigned_by);
create index if not exists role_addon_permissions_permission_idx on public.role_addon_permissions(permission_key);
create index if not exists role_addons_created_by_idx on public.role_addons(created_by);
create index if not exists role_drafts_role_idx on public.role_drafts(role_id);
create index if not exists role_drafts_base_version_idx on public.role_drafts(base_version_id);
create index if not exists role_drafts_created_by_idx on public.role_drafts(created_by);
create index if not exists role_drafts_updated_by_idx on public.role_drafts(updated_by);
create index if not exists role_versions_company_idx on public.role_versions(company_id);
create index if not exists role_versions_created_by_idx on public.role_versions(created_by);
create index if not exists role_versions_published_by_idx on public.role_versions(published_by);
create index if not exists workspace_setting_drafts_created_by_idx on public.workspace_setting_drafts(created_by);
create index if not exists workspace_setting_versions_created_by_idx on public.workspace_setting_versions(created_by);

drop policy if exists scope_rules_manage on public.access_scope_rules;
drop policy if exists entitlement_overrides_manage on public.company_entitlement_overrides;
drop policy if exists member_addons_manage on public.member_role_addons;
drop policy if exists org_unit_memberships_manage on public.organization_unit_memberships;
drop policy if exists org_units_manage on public.organization_units;
drop policy if exists role_addon_permissions_manage on public.role_addon_permissions;
drop policy if exists role_addons_manage on public.role_addons;
